### PR TITLE
feat: add the subinvoke-error case

### PR DESCRIPTION
**Pull request by dOrgJelli**
Added here: https://github.com/polywrap/toolchain/pull/1556

### CODE REVIEW

**Comment by dOrgJelli** [comment]
NOTE: don't merge this yet, see the `CI / Build-And-Run` workflow step. It is actually failing to build & run these test cases, but it is still succeeding.

**Review by cbrzn — COMMENTED** [review]
iiuc, these tests have been already added here:
https://github.com/polywrap/wrap-test-harness/blob/master/cases/subinvoke/00-subinvoke/implementations/rs/lib.rs#L8-L10 and being subinvoked here https://github.com/polywrap/wrap-test-harness/blob/master/cases/subinvoke/01-invoke/implementations/rs/lib.rs#L9-L11. In order to test the two-layers error a `consumer` was created: https://github.com/polywrap/wrap-test-harness/blob/master/cases/subinvoke/02-consumer/implementations/rs/lib.rs#L9-L11

let me know if this make sense to you. also, will dig further in the build error (it should def go red if that happens)

**Comment by cbrzn** [comment]
update: indeed, the current cases are sufficient to cover the errors :smile: - going to close this PR because the other [PR in toolchain](https://github.com/polywrap/toolchain/pull/1476) is green with the expected test cases :yum:

**Comment by cbrzn** [comment]
> NOTE: don't merge this yet, see the `CI / Build-And-Run` workflow step. It is actually failing to build & run these test cases, but it is still succeeding.

@dOrgJelli this was an awesome catch. thank you for noticing this, a fix has been created here: #46

**Pull request closed without merging**
